"""WAF (Web Application Firewall) detection and fingerprinting tool."""

from __future__ import annotations

from typing import Any, Literal

import requests

from strix.tools.registry import register_tool
from strix.tools.validation import (
    generate_usage_hint,
    validate_action_param,
    validate_required_param,
    validate_unknown_params,
)


WAFAction = Literal["detect", "fingerprint", "test_bypass"]


# WAF signatures
WAF_SIGNATURES = {
    "cloudflare": {
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
        "cookies": ["__cfduid", "__cflb"],
        "body_patterns": ["cloudflare", "ray id", "attention required"],
        "status_codes": [403, 503],
    },
    "akamai": {
        "headers": ["x-akamai-", "akamai-"],
        "body_patterns": ["akamai", "reference #"],
        "status_codes": [403],
    },
    "aws_waf": {
        "headers": ["x-amzn-", "x-amz-"],
        "body_patterns": ["aws waf", "request blocked"],
        "status_codes": [403],
    },
    "cloudfront": {
        "headers": ["x-amz-cf-id", "x-cache", "via"],
        "body_patterns": ["cloudfront"],
        "status_codes": [403],
    },
    "imperva": {
        "headers": ["x-cdn"],
        "cookies": ["incap_ses", "visid_incap"],
        "body_patterns": ["incapsula", "imperva"],
        "status_codes": [403],
    },
    "f5_big_ip": {
        "cookies": ["TS", "BigIPServer"],
        "body_patterns": ["f5", "bigip"],
        "status_codes": [403],
    },
    "barracuda": {
        "cookies": ["barra_counter_session"],
        "body_patterns": ["barracuda", "you have been blocked"],
        "status_codes": [403],
    },
    "sucuri": {
        "headers": ["x-sucuri-", "x-sucuri-id"],
        "body_patterns": ["sucuri", "access denied", "blocked by sucuri"],
        "status_codes": [403],
    },
    "wordfence": {
        "body_patterns": ["wordfence", "generated by wordfence"],
        "status_codes": [403, 503],
    },
    "modsecurity": {
        "headers": ["mod_security"],
        "body_patterns": ["mod_security", "modsecurity"],
        "status_codes": [403, 406],
    },
}

# Attack payloads to trigger WAF
ATTACK_PAYLOADS = [
    "' OR '1'='1",  # SQL injection
    "<script>alert(1)</script>",  # XSS
    "../../../../etc/passwd",  # Path traversal
    "{{7*7}}",  # SSTI
    "<?xml version='1.0'?><!DOCTYPE foo [<!ENTITY xxe SYSTEM 'file:///etc/passwd'>]>",  # XXE
]


def _detect_waf(url: str, timeout: int = 10) -> dict[str, Any]:
    """Detect if WAF is present."""
    results = {
        "waf_detected": False,
        "detected_wafs": [],
        "indicators": []
    }
    
    try:
        # Normal request
        normal_response = requests.get(url, timeout=timeout, allow_redirects=False)
        
        # Attack request to trigger WAF
        attack_response = requests.get(
            f"{url}?test=<script>alert(1)</script>",
            timeout=timeout,
            allow_redirects=False
        )
        
        # Check for WAF indicators
        for waf_name, signatures in WAF_SIGNATURES.items():
            matched = False
            
            # Check headers
            if "headers" in signatures:
                for header_pattern in signatures["headers"]:
                    if any(header_pattern.lower() in h.lower() for h in attack_response.headers):
                        results["indicators"].append(f"{waf_name}: Header pattern '{header_pattern}' found")
                        matched = True
            
            # Check cookies
            if "cookies" in signatures:
                cookies = attack_response.cookies.get_dict()
                for cookie_pattern in signatures["cookies"]:
                    if any(cookie_pattern.lower() in c.lower() for c in cookies):
                        results["indicators"].append(f"{waf_name}: Cookie pattern '{cookie_pattern}' found")
                        matched = True
            
            # Check body patterns
            if "body_patterns" in signatures:
                body_lower = attack_response.text.lower()
                for pattern in signatures["body_patterns"]:
                    if pattern.lower() in body_lower:
                        results["indicators"].append(f"{waf_name}: Body pattern '{pattern}' found")
                        matched = True
            
            # Check status codes
            if "status_codes" in signatures:
                if attack_response.status_code in signatures["status_codes"]:
                    if attack_response.status_code != normal_response.status_code:
                        results["indicators"].append(f"{waf_name}: Blocking status code {attack_response.status_code}")
                        matched = True
            
            if matched:
                results["detected_wafs"].append(waf_name)
                results["waf_detected"] = True
        
        # Generic WAF detection
        if attack_response.status_code == 403 and normal_response.status_code == 200:
            if not results["waf_detected"]:
                results["waf_detected"] = True
                results["indicators"].append("Generic WAF: Request blocked (403) on attack payload")
        
    except requests.exceptions.RequestException as e:
        results["error"] = str(e)
    
    return results


def _test_bypass_techniques(url: str, timeout: int = 10) -> dict[str, Any]:
    """Test WAF bypass techniques."""
    results = {
        "bypass_techniques": [],
        "tests": []
    }
    
    # Original attack payload
    original_payload = "<script>alert(1)</script>"
    
    # Bypass techniques
    bypass_payloads = {
        "case_variation": "<ScRiPt>alert(1)</sCrIpT>",
        "double_encoding": "%253Cscript%253Ealert(1)%253C%252Fscript%253E",
        "null_byte": "<script>alert(1)</script>%00",
        "comment_injection": "<scr<!--comment-->ipt>alert(1)</scr<!---->ipt>",
        "newline": "<script>\nalert(1)\n</script>",
        "tab": "<script>\talert(1)\t</script>",
        "unicode": "\\u003cscript\\u003ealert(1)\\u003c/script\\u003e",
        "mixed": "<ScR%69pt>al%65rt(1)</sCr%69pt>",
    }
    
    for technique, payload in bypass_payloads.items():
        test_result = {
            "technique": technique,
            "payload": payload,
        }
        
        try:
            response = requests.get(
                f"{url}?test={payload}",
                timeout=timeout,
                allow_redirects=False
            )
            
            test_result["status_code"] = response.status_code
            test_result["blocked"] = response.status_code == 403
            
            # Check if payload is reflected (possible bypass)
            if payload in response.text or "alert(1)" in response.text:
                test_result["reflected"] = True
                test_result["potential_bypass"] = True
                results["bypass_techniques"].append(technique)
            else:
                test_result["reflected"] = False
            
        except requests.exceptions.RequestException as e:
            test_result["error"] = str(e)
        
        results["tests"].append(test_result)
    
    return results


@register_tool
def waf_detector(
    action: WAFAction,
    url: str,
    timeout: int = 10
) -> str:
    """Detect and fingerprint Web Application Firewalls (WAF).
    
    Identifies presence of WAF and attempts to fingerprint the specific
    WAF vendor. Also tests common bypass techniques.
    
    Args:
        action: Action to perform
            - detect: Detect if WAF is present
            - fingerprint: Identify specific WAF vendor
            - test_bypass: Test WAF bypass techniques
        url: Target URL for testing
        timeout: Request timeout in seconds
    
    Returns:
        Detection results and WAF fingerprint information
    """
    if not url:
        return "Error: URL required for WAF detection"
    
    if action == "detect":
        results = _detect_waf(url, timeout)
        
        output = ["WAF Detection Results", "=" * 50, ""]
        output.append(f"Target: {url}")
        output.append(f"WAF Detected: {results['waf_detected']}")
        output.append("")
        
        if results["detected_wafs"]:
            output.append("Detected WAF(s):")
            for waf in results["detected_wafs"]:
                output.append(f"  ✓ {waf.upper()}")
            output.append("")
        
        if results["indicators"]:
            output.append("Detection Indicators:")
            for indicator in results["indicators"]:
                output.append(f"  • {indicator}")
        
        if "error" in results:
            output.append(f"\nError: {results['error']}")
        
        return "\n".join(output)
    
    elif action == "fingerprint":
        results = _detect_waf(url, timeout)
        
        output = ["WAF Fingerprinting Results", "=" * 50, ""]
        output.append(f"Target: {url}")
        output.append("")
        
        if not results["waf_detected"]:
            output.append("No WAF detected")
        elif not results["detected_wafs"]:
            output.append("WAF detected but vendor unknown (generic detection)")
            output.append("")
            output.append("Indicators:")
            for indicator in results["indicators"]:
                output.append(f"  • {indicator}")
        else:
            output.append("Identified WAF Vendor(s):")
            for waf in results["detected_wafs"]:
                output.append(f"\n{waf.upper()}:")
                
                # Show matching indicators for this WAF
                waf_indicators = [i for i in results["indicators"] if waf in i.lower()]
                for indicator in waf_indicators:
                    output.append(f"  • {indicator}")
        
        return "\n".join(output)
    
    elif action == "test_bypass":
        # First detect WAF
        detect_results = _detect_waf(url, timeout)
        
        output = ["WAF Bypass Testing", "=" * 50, ""]
        output.append(f"Target: {url}")
        output.append("")
        
        if not detect_results["waf_detected"]:
            output.append("No WAF detected. Bypass testing not applicable.")
            return "\n".join(output)
        
        if detect_results["detected_wafs"]:
            output.append(f"Detected WAF: {', '.join(detect_results['detected_wafs']).upper()}")
        else:
            output.append("Detected WAF: Generic/Unknown")
        output.append("")
        
        # Test bypass techniques
        bypass_results = _test_bypass_techniques(url, timeout)
        
        output.append("Bypass Technique Results:")
        for test in bypass_results["tests"]:
            output.append(f"\n{test['technique']}:")
            if "error" in test:
                output.append(f"  Error: {test['error']}")
            else:
                blocked = "BLOCKED" if test.get("blocked") else "NOT BLOCKED"
                output.append(f"  Status: {blocked} ({test['status_code']})")
                output.append(f"  Reflected: {test.get('reflected', False)}")
                
                if test.get("potential_bypass"):
                    output.append("  ✓ POTENTIAL BYPASS!")
        
        if bypass_results["bypass_techniques"]:
            output.append("")
            output.append("⚠ Potential Bypass Techniques:")
            for technique in bypass_results["bypass_techniques"]:
                output.append(f"  • {technique}")
        else:
            output.append("")
            output.append("No bypass techniques successful with tested payloads.")
        
        return "\n".join(output)
    
    return "Invalid action. Use: detect, fingerprint, test_bypass"
